twilio/twilio-cli-core

src/base-commands/twilio-client-command.js, src/services/config.js, test/base-commands/twilio-client-command.test.js, test/services/config.test.js
=> Add project region support

.vscode/launch.json, src/base-commands/base-command.js, src/base-commands/twilio-client-command.js
Not all commands (especially help) need inquirer (~200ms load time) or twilio (~600ms), so this PR lazy-loads them when they are needed.
=> Lazy load inquirer and twilio for better load perf

src/services/javascript-utilities.js, test/services/javascript-utilities.test.js
=> Add a utility for splitting arrays based on a function

src/services/messaging/logging.js, test/services/messaging/logging.test.js
=> Add a global logger instance so we can log/print easily wherever

package-lock.json, package.json, src/base-commands/twilio-client-command.js, src/services/config.js, test/base-commands/twilio-client-command.test.js, test/services/config.test.js
=> switches from default project to active project

src/base-commands/twilio-client-command.js, test/base-commands/twilio-client-command.test.js
=> Switch the 'project' topic to 'projects'

src/services/config.js, src/services/env.js, src/services/secure-storage.js, test/services/env.test.js
=> Move the config directory to '.twilio-cli'

README.md, src/base-commands/base-command.js, src/base-commands/twilio-client-command.js, src/index.js, src/services/cli-http-client.js, src/services/error.js, src/services/messaging/help-messages.js, test/base-commands/twilio-client-command.test.js, test/services/cli-http-client.test.js
=> Refactor the base commands to expose more functionality

src/services/secure-storage.js
Added removeCredentials function to secure-storage to remove local key.
=> Added removeCredentials function to secure-storage

package.json, src/services/cli-http-client.js
Drops `lodash`, `q`, and `twilio` dependencies in the request client
=> Simplify the CLI request client

src/services/javascript-utilities.js, src/services/naming-conventions.js, test/services/javascript-utilities.test.js, test/services/naming-conventions.test.js
=> Add some super rad utils

package.json
=> Add Keytar as a peer and dev dependency

src/services/config.js
Add in email object to store default email address and default subject line.
=> Default sending email and subject line

src/services/open-api-client.js, test/services/twilio-api/twilio-client.test.js
=> Add support for next page links that are relative or absolute

README.md, src/base-commands/twilio-client-command.js, src/services/config.js, src/services/secure-storage.js, test/base-commands/twilio-client-command.test.js, test/services/config.test.js
=> breaking: Switch naming from 'project(s)' to 'profile(s)'

src/base-commands/base-command.js, test/base-commands/twilio-client-command.test.js, test/services/secure-storage.test.js
Adds tests for getting credentials with a keytar mock.
=> Remove implicit test dependency on keytar presence

.travis.yml
=> Auto-deploy using Travis CI upon tagged commit to master

.travis.yml
The npm key needs to be generated within the repo.
=> Update npm key

src/services/twilio-api/twilio_api.json, src/services/twilio-api/twilio_taskrouter.json, src/services/twilio-api/twilio_voice.json
Update autogenerated Open API definitions
=> Update Open API definitions

package-lock.json, package.json, src/base-commands/base-command.js, src/services/require-install.js, src/services/secure-storage.js, test/services/require-install.test.js, test/services/secure-storage.test.js
Fixes https://github.com/twilio/twilio-cli/issues/119
=> fix: dynamically install keytar if it fails to load

.travis.yml
=> fix: update travis deploy

package.json
=> fix: npm audit vulnerabilities

src/services/config.js, test/services/config.test.js
Closes [DI-1475](https://issues.corp.twilio.com/browse/DI-1475)
As we are adding a new JSON object for profiles, the existing code using the profiles object (which is reading the projects array) is being refactored. 
Dependent PR in twilio-cli : [Link](https://github.com/twilio/twilio-cli/pull/257)
- Tested Unit Tests : [Test Report Link](https://gist.github.com/onuzbee/4d64268a7927b4b472e6f0c4757057dd)
- Tested profiles usage - create/remove/list manually 
=> chore: Refactor profiles usage to projects

src/services/config.js, test/services/config.test.js
Closes : [DI-1350](https://issues.corp.twilio.com/browse/DI-1350)
Dependent PR: [Link](https://github.com/twilio/twilio-cli/pull/259) 
Changes in profiles:create to add api keys in config file. 
Testing Gist : [Link](https://gist.github.com/onuzbee/2cfa2477ece0ce39118312428859d99c)
=> chore: Store API Keys in Config File

.nycrc.json, .travis.yml, package.json, sonar-project.properties, src/services/config.js
Closes [DI-1381](https://issues.corp.twilio.com/browse/DI-1381)
Integrates with Sonarcloud and adds a PR Quality Gate. 
=> chore: Integrate with Sonarcloud

src/base-commands/base-command.js, src/services/output-formats/index.js, test/base-commands/base-command.test.js
Adds `none` output type, and `silent` flag which is a substitute for suppressing ALL output. 
Screenshot: 
=> chore: Add none output and silent flag

.travis.yml
Added change to deploy specific regex match tags.
=> fix: Added condition to deploy specific regex match tags

src/services/cli-http-client.js, test/services/cli-http-client.test.js
Closes [DII-45](https://issues.corp.twilio.com/browse/DII-45)
Screenshot: 
=> chore: Fixes exit codes

src/services/cli-http-client.js, test/services/cli-http-client.test.js
Pulling recent commits from main
=> SR: Fixing exit codes (#142)

.github/workflows/release.yml
=> Corrected the homebrew inputs for the workflow

.releaserc.json
Workaround for the semantic github plugin issue.
=> Fixed the semantic github issue

src/services/twilio-api/twilio_messaging_v1.json
Related PR: https://github.com/twilio/twilio-oai/pull/44
=> fix: fix parameter naming 

.github/workflows/release.yml
Closes [DII-134](https://issues.corp.twilio.com/browse/DII-134): Fixing the protected branch issue.
Workflow Runs: [Failed Run](https://github.com/ravali-rimmalapudi/twilio-cli-core/runs/3728882137?check_suite_focus=true#step:6:66), [Passed Run](https://github.com/ravali-rimmalapudi/twilio-cli-core/runs/3729045192?check_suite_focus=true#step:6:64)
BranchProtection: [Enabled](https://github.com/ravali-rimmalapudi/twilio-cli-core/settings/branches)
=> Fixing the protected branch issue

.github/scripts/trigger-workflow.js, .github/scripts/update-api-spec-with-changelog.sh, .github/scripts/update-release.js, .github/workflows/release.yml, .releaserc.json, package.json
1. Updated OAI commit not to include in the release notes
2. Updated github dependencies
3. Eslint fixes
Closes: [DII-133](https://issues.corp.twilio.com/browse/DII-133)
Dependent PR: [CLI](https://github.com/twilio/twilio-cli/pull/301
)
=> fix:Added the following changes:

package.json
Fix `ansi-regex` security vulnerability. 
=> Fix: Resolve sec vulnerability

src/services/twilio-api/twilio_api_v2010.json, src/services/twilio-api/twilio_autopilot_v1.json, src/services/twilio-api/twilio_fax_v1.json
Fixes [DII-132](https://issues.corp.twilio.com/browse/DII-132)
This PR: 
Solves the [indentation issue](https://github.com/jamestalmage/supports-hyperlinks/issues/13) introduced via dependency supports-hyperlink (to convert markdowns into url).
Alternative dependencies aren't compliant with node 10.x. 
Before: 
After:
=> fix: Modified flag descriptions to eliminate new line indentation issue

.releaserc.json
Removed change to stop publish from npm.
=> fix: Removed change to stop publish from npm.

.github/scripts/trigger-workflow.js
If there were no changes in the OAI, there used to be a null pointer error. This has been fixed. 
Fixes : [DII-172](https://issues.corp.twilio.com/browse/DII-172)
Testing: 
[CLI-core actions](https://github.com/shamantraghav/twilio-cli-core/actions/runs/1462929085)
[CLI action getting triggered](https://github.com/shamantraghav/twilio-cli/actions/runs/1462941140)
=> fix: Triggering cli from cli-core

src/base-commands/base-command.js, src/base-commands/twilio-client-command.js
Closes: [DII-12](https://issues.corp.twilio.com/browse/DII-12)
=> Add flag no header for list and fetch commands

.github/workflows/cli-core-test.yml, .github/workflows/release.yml
changes to use Makefile script instead of npm commands
test run: https://github.com/kridai/twilio-cli-core/actions/runs/1535093551
=> chore: github workflow update

package.json
=> chore: Remove audit run with posttest script

.github/workflows/release.yml
=> fix: Update semantic-release via npm bin

.github/scripts/validate_cli_tokens.py, .github/workflows/release.yml
Test case where CLI tokens are invalid: 
https://github.com/shamantraghav/twilio-cli-core/actions/runs/1822859463
Test case where CLI tokens are valid: 
https://github.com/shamantraghav/twilio-cli-core/actions/runs/1822868587
Also review: https://github.com/twilio/twilio-cli/pull/389
=> Changes to validate CLI tokens

.github/scripts/create-fork-pipeline-changes.js, .github/workflows/release.yml, Makefile
Run workflow pipeline on fork main repo for testing [DII-314](https://issues.corp.twilio.com/browse/DII-314)
=> Enable developers to run pipeline on fork main repo for testing

.github/workflows/cli-core-audit.yml, .github/workflows/cli-core-test.yml, .github/workflows/release.yml
https://issues.corp.twilio.com/browse/DII-320
=> chore: Add node v12 support

src/services/twilio-api/api-browser.js, test/services/twilio-api/api-browser.test.js
This PR: 
YPS would have `preview` spec enabled now (PR [link](https://code.hq.twilio.com/twilio/yps/pull/100)) to facilitate helper libraries. 
Twilio-cli needs to skip it. 
[Gist](https://gist.github.com/shrutiburman/f36985c690953c9a3276849670e75ece)
=> feat: skip loading preview spec

test/services/twilio-api/twilio-client.test.js
Test logs: https://github.com/twilio/twilio-cli-core/runs/7554389676?check_suite_focus=true
=> Fixing broken test

.github/scripts/update-release.js
Fixes ocktokit api calls in update-release.js script
Screenshot of working API calls made in a test script:
=> fix: Fixing ocktokit api calls

.github/scripts/update-release.js
Relevant PR: https://github.com/twilio/twilio-cli-core/pull/211
=> fix: octokit API call fix 

package.json
Also merge: https://github.com/twilio/twilio-cli/pull/463
=> Updating @oclif plugins version

.github/workflows/release.yml
Release was failing because of npm bin at semantic release step.
https://github.com/twilio/twilio-cli-core/actions/runs/4249713380/jobs/7390157614
=> fix: using npx instead of npm bin

.github/scripts/update-release.js, .github/workflows/release.yml
Enable RC release for cli-core.
In case of main and RC release, cli-core will be calling cli two times one for main branch(MVR release) and other for RC branch.
Main release is mandatory from cli-core. RC is optional and can not be done alone from cli-core.
=> chore: enabled rc release

Dockerfile
=> fix: Update Dockerfile base to be consistent with twilio-cli

src/services/twilio-api/api-browser.js
A new healthcheck api is created in oai specs we need skip that:
https://github.com/twilio/twilio-oai/commit/45eef8d415c95ba25f6556b7e71c5f45afc0973c#diff-5d1f980b58be3379b445cfb53a6bd81ca4dd5ee457d7cd2df29348c1c5743905R35309
=> chore: skip healthcheck api

src/services/twilio-api/api-browser.js
A new healthcheck api is created in oai specs we need skip that:
https://github.com/twilio/twilio-oai/commit/45eef8d415c95ba25f6556b7e71c5f45afc0973c#diff-5d1f980b58be3379b445cfb53a6bd81ca4dd5ee457d7cd2df29348c1c5743905R35309
=> chore: skipped healthcheck api

README.md, package-lock.json
=> enable-release-commit

README.md, package-lock.json
Reverts twilio/twilio-cli-core#241
=> fix: Revert enable-release-commit

src/services/naming-conventions.js
The kebabCase conversion in cli-core (See [here](https://github.com/twilio/twilio-cli-core/blob/eb93b79293b167b51aaf0e96669e1434d9d64723/src/services/naming-conventions.js#L1)) is slightly different from snakeCase conversion in Oai-generator (see [here](https://github.com/twilio/twilio-oai-generator/blob/main/src/main/java/com/twilio/oai/StringHelper.java#L16)). 
For example, the parameter 'A2PProfileBundleSid' translates to 'a2-pprofile-bundle-sid` in cli whereas the correct conversion to 'a2p_profile_bundle_sid' happens in oai-generator.
Making them consistent.
=> fix: corrected kebabCase for parameters with numbers

src/services/naming-conventions.js
Fixing kebab-case number error, corrects the regex of this [PR](https://github.com/twilio/twilio-cli-core/pull/246)
=> chore: fixing kebab-case error

package.json
this fixes recent https://github.com/advisories/GHSA-8hc4-vh64-cxmj Server-Side Request Forgery in axios (https://github.com/advisories/GHSA-8hc4-vh64-cxmj)
=> chore: fixed axios vulnerability by upgrading to 1.7.4

package.json
twilio 5.3.0 and later uses axios 1.7.4 and later which is free from security vulnerability
=> chore: update twilio version to use patched axios version

.github/workflows/release.yml
=> chore: add debug logic

package-lock.json, package.json
Bumping `mock-fs` to latest version `5.4.1` to fix [test failure](https://github.com/twilio/twilio-cli-core/actions/runs/12688846971/job/35366406322#logs). Possibly the older versions have some bugs introduced since it is not able to mock the required files. 
=> chore: bump mock-fs version to fix test failure

package-lock.json, package.json
=> chore: upgrade mockfs version

package-lock.json, package.json
Fixing mock-fs to a given version to fix this [test](https://github.com/twilio/twilio-cli-core/actions/runs/14058524064/job/39363707582#step:6:106)
=> chore: fix mock-fs version to fix test failure

.github/workflows/release.yml
Reverts twilio/twilio-cli-core#262
=> fix: revert use node 18 to update api specs

.github/workflows/release.yml
Pointing to node 18 to fix the release job failure
=> chore: point to node 18 for release job

.github/workflows/release.yml
=> fix: add dummy commit

README.md
=> oaiFix: Update README.md

README.md
=> BREAKING CHANGE : Update README.md

README.md
=> BREAKING CHANGE: Update README.md

.github/scripts/update-api-spec-with-changelog.sh
If there are no changes coming from OAI specs, default release will be of type patch
Otherwise, it will take from the OAI spec versionType
=> chore: take default patch versiontype

.github/workflows/release.yml, package-lock.json
Adding post build checks to ensure that new cli-core version is not breaking anything in twilio-cli before triggering its release.
This ensures that the issue caused by twilio-cli-core will be caught in the release workflow of twilio-cli-core only and not in twilio-cli release workflow.
Here is a [test run](https://github.com/twilio/twilio-cli-core/actions/runs/16313485300/job/46073794347) of how this script will run.
=> chore: test cli-core released version before triggering cli release

package.json
Upgrading axios version for the this security vulnerability - https://github.com/twilio/twilio-cli-core/security/dependabot/45
=> chore: upgrade axios version

src/services/twilio-api/api-browser.js
In the last release, a spec file was added to twilio-oai called [twilio_voice_oneconsole](https://github.com/twilio/twilio-oai/blob/main/spec/json/twilio_voice_oneconsole.json). This file has empty paths and does not have components and schemas which are validated in cli-core. Hence skipping the spec file for now.
=> chore: skip twilio_voice_oneconsole.json due to missing components
