- src/base-commands/twilio-client-command.js
- src/services/config.js
- test/base-commands/twilio-client-command.test.js
- test/services/config.test.js
> Use env vars first for credentials if no project is specified

- package-lock.json
- package.json
- src/base-commands/base-command.js
---
Now you see something like this:
```
➜  twilio api:core:incoming-phone-numbers:list --help
Retrieve a list of incoming-phone-numbers belonging to the account used to make the request.
USAGE
$ twilio api:core:incoming-phone-numbers:list
OPTIONS
-l=(debug|info|warn|error|none)  [default: info] Level of logging messages.
-o=(columns|json|tsv)            [default: columns] Format of command output.
-p, --project=project            Shorthand identifier for your Twilio project.
--account-sid=account-sid        The SID of the Account that created the resources to read
--beta …
```
> Rename the base command flags to reduce chance of conflict with auto-generated commands

- src/base-commands/base-command.js
- test/base-commands/base-command.test.js
Previously the date output was too long. This PR removes the day of the week and the local time zone. It should also standardize the output to display month day year hours:minutes:seconds and off set from GMT time.
> Condensed and standardized date output

- src/services/config.js
- test/services/config.test.js
Refactored `getProjectById` to use the new `getActiveProject` function that returns the active project. Added the `removeProject` function that will removed specific project.
> Remove project

- src/index.js
- src/services/naming-conventions.js
- src/services/resource-path-parser.js
- test/services/naming-conventions.test.js
- test/services/resource-path-parser.test.js
These will be used by the new client that's going in core for now.
Straight cut-paste from the cli: https://github.com/twilio/twilio-cli/tree/bb9524e78f6082276ce102aa218cdc0ec0c07d40/src/services
> Move naming and resource path utilities to core

- package.json
Pending this fix: https://github.com/atom/node-keytar/issues/196
> Temporarily pin keytar

- src/services/twilio-api/twilio_api.json
- src/services/twilio-api/twilio_authy.json
- src/services/twilio-api/twilio_autopilot.json
- src/services/twilio-api/twilio_chat.json
- src/services/twilio-api/twilio_fax.json
- src/services/twilio-api/twilio_insights.json
- src/services/twilio-api/twilio_lookups.json
- src/services/twilio-api/twilio_messaging.json
- src/services/twilio-api/twilio_monitor.json
- src/services/twilio-api/twilio_notify.json
- src/services/twilio-api/twilio_numbers.json
- src/services/twilio-api/twilio_preview.json
- src/services/twilio-api/twilio_pricing.json
- src/services/twilio-api/twilio_proxy.json
- src/services/twilio-api/twilio_serverless.json
- src/services/twilio-api/twilio_studio.json
- src/services/twilio-api/twilio_sync.json
- src/services/twilio-api/twilio_taskrouter.json
- src/services/twilio-api/twilio_trunking.json
- src/services/twilio-api/twilio_verify.json
- src/services/twilio-api/twilio_video.json
- src/services/twilio-api/twilio_voice.json
- src/services/twilio-api/twilio_wireless.json
`patternProperties` not currently support by OAS v3: https://github.com/OAI/OpenAPI-Specification/issues/687
Proper `null` handling docs: https://swagger.io/docs/specification/data-models/data-types/#null
Docs on string formatting: https://swagger.io/docs/specification/data-models/data-types/#format
> Drop unsupported null-type object, patternProperties, and add RFC 2822 date time format

- src/services/twilio-api/api-browser.js
- src/services/twilio-api/index.js
- test/services/twilio-api.test.js
Drops the 'version' grouping and adds HTTP method/operation names.
> breaking: Make the API browser more generic

- package-lock.json
- package.json
- src/base-commands/twilio-client-command.js
- src/services/api-schema/json-converter.js
- src/services/api-schema/twilio-converter.js
- src/services/cli-http-client.js
- src/services/naming-conventions.js
- src/services/open-api-client.js
- src/services/output-formats/columns.js
- src/services/twilio-api/api-browser.js
- src/services/twilio-api/index.js
- src/services/twilio-api/twilio-client.js
- test/services/api-schema.test.js
- test/services/twilio-api/api-browser.test.js
- test/services/twilio-api/twilio-client.test.js
> Add a TwilioAPI client based on the Twilio OpenAPI spec

- src/services/cli-http-client.js
- src/services/twilio-api/twilio-client.js
This change allows commands using the Node helper lib to catch a TwilioCliError
when a non-2XX response is received.
> Move the non-2XX error handling down to the CliRequestClient

- src/base-commands/twilio-client-command.js
- test/base-commands/twilio-client-command.test.js
Allows using a sub-account-sid when managing resources for a sub-account.
> Allow specifying a sub account sid for commands

- src/base-commands/base-command.js
- test/base-commands/base-command.test.js
Before:
```
> twilio api:core:incoming-phone-numbers:list --properties "dateCreated,capabilities"
Date Created                   Capabilities   
Jan 09 2019 18:22:24 GMT-0600  [object Object]
May 20 2019 09:34:18 GMT-0500  [object Object]
May 20 2019 09:31:47 GMT-0500  [object Object]
```
After:
```
> twilio api:core:incoming-phone-numbers:list --properties "dateCreated,capabilities"
Date Created                   Capabilities                         
Jan 09 2019 18:22:24 GMT-0600  {"mms":true,"sms":true,"voice":true} 
May 20 2019 09:34:18 GMT-0500  {"mms":false,"sms":true,"voice":true}
May 20 2019 09:31:47 GMT-0500  {"mms":true,"sms":true,"voice":true} 
```
> String-ify objects in columnar and TSV output formats

- src/services/twilio-api/twilio_api.json
- src/services/twilio-api/twilio_preview.json
- src/services/twilio-api/twilio_proxy.json
The case of these properties is inconsistent across APIs so we'll no longer
explicitly list them.
Before:
```
> twilio api:core:available-phone-numbers:mobile:list --country-code GB --properties="phoneNumber,capabilities"
Phone Number   Capabilities  
+447723568014  {"voice":true}
+447723474023  {"voice":true}
```
After:
```
> twilio api:core:available-phone-numbers:mobile:list --country-code GB --properties="phoneNumber,capabilities"
Phone Number   Capabilities                                    
+447723582205  {"voice":true,"sms":true,"mms":false,"fax":true}
+447723486799  {"voice":true,"sms":true,"mms":false,"fax":true}
```
> Drop specific properties from 'phone_number_capabilities' types

- src/services/twilio-api/twilio_accounts.json
- src/services/twilio-api/twilio_api.json
- src/services/twilio-api/twilio_authy.json
- src/services/twilio-api/twilio_autopilot.json
- src/services/twilio-api/twilio_chat.json
- src/services/twilio-api/twilio_conversations.json
- src/services/twilio-api/twilio_fax.json
- src/services/twilio-api/twilio_flex.json
- src/services/twilio-api/twilio_messaging.json
- src/services/twilio-api/twilio_monitor.json
- src/services/twilio-api/twilio_notify.json
- src/services/twilio-api/twilio_preview.json
- src/services/twilio-api/twilio_pricing.json
- src/services/twilio-api/twilio_proxy.json
- src/services/twilio-api/twilio_serverless.json
- src/services/twilio-api/twilio_studio.json
- src/services/twilio-api/twilio_sync.json
- src/services/twilio-api/twilio_taskrouter.json
- src/services/twilio-api/twilio_trunking.json
- src/services/twilio-api/twilio_verify.json
- src/services/twilio-api/twilio_video.json
- src/services/twilio-api/twilio_voice.json
- src/services/twilio-api/twilio_wireless.json
Twilio docs: https://www.twilio.com/docs/usage/twilios-response?code-sample=code-paging-information-4
> Add 'PageSize' parameter to all 'read' actions

- src/base-commands/twilio-client-command.js
- src/services/messaging/help-messages.js
- test/base-commands/twilio-client-command.test.js
Output:
```
➜  twilio api:core:incoming-phone-numbers:list --profile="ugh ugh"
» Could not find profile "ugh ugh".
» To create the profile, run:
twilio profiles:create --profile "ugh ugh"
Alternatively, twilio-cli can use credentials stored in environment variables:
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_API_KEY = an API Key created at twil.io/get-api-key
TWILIO_API_SECRET = the secret for the API Key
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_AUTH_TOKEN = your Auth Token from twil.io/console
Once these environment variables are set, a twilio-cli profile is not required to move forward with installation.
```
And:
```
➜  twilio login
» Secure credential storage failed to load.
Alternatively, twilio-cli can use credentials stored in …
```
> fix: update the wording for the env vars help message

- src/services/api-schema/twilio-converter.js
- test/services/api-schema.test.js
Studio flow definition keys were being converted to camelCase which was breaking updates that use the same definition.
> fix: only camelCase object keys when a schema is specified for the value

- src/base-commands/twilio-client-command.js
- src/services/config.js
- src/services/open-api-client.js
- src/services/twilio-api/twilio-client.js
- test/base-commands/twilio-client-command.test.js
- test/services/config.test.js
- test/services/twilio-api/twilio-client.test.js
https://issues.corp.twilio.com/browse/DI-646
> feat: add regional and edge support

- src/base-commands/base-command.js
- src/services/messaging/help-messages.js
- src/services/messaging/templates.js
- src/services/require-install.js
- test/base-commands/base-command.test.js
Rather than have the twilio-cli GitHub issues link used for all uncaught exceptions, use that of the plugin for plugin commands. This change will attempt to find the plugin bugs/homepage/repo URL when a plugin command extending our `BaseCommand` throws an uncaught exception. If found, it will be used as part of the error message. Otherwise, it will fallback to use the standard twilio-cli URL.
> feat: look through plugin pjson for an issue URL

- src/services/require-install.js
- test/services/require-install.test.js
If we're able to successfully load/install a runtime dependency, this change prevents any errors from being logged since we were successful in the end. This was confusing customers when they see things like keytar errors during the install process when everything's actually fine.
> fix: delay module-loading error logs until all locations have been exhausted

- src/base-commands/twilio-client-command.js
- test/base-commands/twilio-client-command.test.js
If you've not created a profile yet and attempt to run a command that requires auth, you would see that the profile "undefined" could not be found. This change just updates the wording to indicate that a profile could not be found to use.
Relates to https://github.com/twilio/twilio-cli/issues/148
> fix: don't display "undefined" when no profiles exists

- src/services/open-api-client.js
- test/services/twilio-api/twilio-client.test.js
When referencing a resource by a unique name with non-safe characters, it needs to be URI-encoded or the request will fail.
Relates to https://github.com/twilio/twilio-node/issues/409
> fix: encode URL path params

- src/base-commands/twilio-client-command.js
- src/services/messaging/help-messages.js
- test/base-commands/twilio-client-command.test.js
Fixes https://github.com/twilio/twilio-cli/issues/146
When users attempt to access resources that require auth greater than what Standard API Keys grant, they are met with an access denied error. Since CLI profiles use such keys, messaging has been added instructing how to use non-standard auth when working with such resources.
> feat: improve 'access denied' error messaging

- package.json
Pinning of tslib no longer required since '@oclif/plugin-plugins' has been fixed. Also, ignore low severity vulnerabilities until lodash issue is resolved: https://www.npmjs.com/advisories/1523
> fix: upgrade dependencies and drop tslib pinning

- src/services/messaging/logging.js
We should not use specific colors for coloring text because it could conflict with the terminal's background color.
> fix: don't get so fancy with the font color scheme

- .travis.yml
- src/services/cli-http-client.js
- src/services/twilio-api/twilio_chat.json
- src/services/twilio-api/twilio_conversations.json
- src/services/twilio-api/twilio_preview.json
- src/services/twilio-api/twilio_sync.json
- src/services/twilio-api/twilio_verify.json
This PR adds the open api specifications for custom header parameters supported by Twilio API endpoints, as well as additional relevant debugger output. 
> feat: add custom header param support

- src/services/cli-http-client.js
- test/services/twilio-api/twilio-client.test.js
Fetching a BulkExport for a single day returns a `307` with the AWS URL for the file. With this change, the URL will now be included in the CLI response.
https://www.twilio.com/docs/usage/bulkexport/day?code-sample=code-fetch-a-single-file-for-an-exported-day
Fixes https://github.com/twilio/twilio-cli/issues/207
> fix: allow API redirect responses

- src/services/open-api-client.js
- test/services/twilio-api/twilio-client.test.js
This commit fixes a bug that happens when the operation's parameters are absent.
Accordingly to OpenAPI spec, operation parameters are not mandatory,
however, the existing code is expecting it.
Dependency of https://github.com/twilio/twilio-cli/pull/230
> fix: getParams when operation parameters is absent

- src/base-commands/base-command.js
- src/services/config.js
- test/services/config.test.js
Plugins can read `this.userConfig` but they can't use it to set other data. I am writing a plugin that I think would benefit from a central config store and writing data to `this.userConfig` would be ideal.
I am proposing that we add a `plugins` property to the object and allow for plugins to add arbitrary data under their own namespace. e.g.
```javascript
this.userConfig.setPluginData('my-new-plugin', { this: 'is', really: 'cool' });
this.userConfig.getPluginData('my-new-plugin').really;
// => 'cool';
```
> feat: allow plugins to use the userConfig object to set arbitrary data 

- src/base-commands/base-command.js
When connecting the plugin config to the base command, I passed through the result of `getCommandPlugin(this)` which is a plugin object and not a string. This lead to `path.join` throwing an error. 🤦‍♂️ 
This fixes that.
> fix: need to use the plugin name, not the plugin object

- src/services/config.js
- test/services/config.test.js
Closes : [DI-1352](https://issues.corp.twilio.com/browse/DI-1352)
Dependent PR: [Link](https://github.com/twilio/twilio-cli/pull/262)
TestCases Gist : [Link](https://gist.github.com/ravali-rimmalapudi/dcce54593a8609da219e4de0fe25c166)
Changes in profiles remove : Check and Use config file before checking system keychain.
> chore: CLI Profile Remove - Check and Use config file before checking system keychain.

- src/base-commands/twilio-client-command.js
- src/services/cli-http-client.js
- test/services/cli-http-client.test.js
Closes [ DI-1354](https://issues.corp.twilio.com/browse/DI-1354)
- [x ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-cli-core/blob/main/CONTRIBUTING.md) and my PR follows them
- [x ] I have titled the PR appropriately
> schamala@C02DV9JRMD6M twilio-cli % ./bin/run debugger:logs:list -l debug
> [DEBUG] Config File: /Users/schamala/.twilio-cli/config.json
> [DEBUG] Using profile: schamala
> [DEBUG] Found command "debugger:logs:list" plugin: twilio-cli
> [DEBUG] Found keytar version in "@twilio/cli-core" optionalDependencies: ^7.6.0
> …
> feat: add keytar word to user agent

- src/base-commands/twilio-client-command.js
- src/services/config.js
- test/base-commands/twilio-client-command.test.js
- test/services/config.test.js
Closes : [DI-1479](https://issues.corp.twilio.com/browse/DI-1479)
Dependent PR: [CLI](https://github.com/twilio/twilio-cli/pull/267),[CLI-TEST](https://github.com/twilio/twilio-cli-test/pull/8)
Changes in active profile: Throwing the error when active profile is NULL and no environment variable is set in case of any command that requires API keys.
Testing Gist : [Link](https://gist.github.com/ravali-rimmalapudi/0b30305e21dd16e9b20d5cfa65de32f5)
> chore: Throw alert when active profile is not set.

- src/base-commands/twilio-client-command.js
- src/services/config.js
- test/base-commands/twilio-client-command.test.js
Closed : DI-424
Added support to make profile input mandatory based on config property. Introduced a new flag to be stored in config.
Testing Gist: [Link](https://gist.github.com/kridai/72e5962a40834815d5b8f79579112c93)
Screenshot
> feat:  Added support to make profile input mandatory based on config property

- src/base-commands/twilio-client-command.js
- src/services/cli-http-client.js
- test/services/cli-http-client.test.js
Closes [DII-72](https://issues.corp.twilio.com/browse/DII-72)
This PR is for standardising the userAgent string format to gain better insights about the metrics involved with cli like usage, potential demand, etc.
Suggested Format:
`<core-api-lib>/<core-api-lib-version> (<os-name> <os-arch>) <extensions>`
Where `<extensions>` are being added space separated following:
`<library>/<library-version>`
or
`<tag>`
**Testing details:** 
[Gist](https://gist.github.com/shrutiburman/655bf08a0fac79e9d25c1572bb73c30e)
Earlier, this is how the UserAgent string looked like:
UserAgent string after the change:
The userAgent string contains keytar flag and the cli version too as per [this](https://docs.google.com/document/d/1qiI_3ziL1OyEqDm348RHneTUj7fiaRHP_zlnzmpav4w/edit#) doc.
> chore: standardize User-Agent string: format and include more details

- .github/scripts/trigger-workflow.js
- .github/scripts/update-release.js
- .github/workflows/release.yml
- package.json
- src/index.js
Conversion of community Github actions into scripts.
> chore:Added changes to use scripts instead of community Github actions

- .github/workflows/cli-core-test.yml
- package.json
Added changes to fix the lcov issue.
> fix: Added changes to fix the lcov issue

- package.json
Bump `axios` to eliminate the security [vulnerability](https://github.com/advisories/GHSA-74fj-2j2h-c42q) caused by `follow-redirects`. 
Issue link : https://github.com/axios/axios/pull/4379
Release: https://github.com/axios/axios/releases/tag/v0.25.0
> chore: bump axios dependency 

- src/services/twilio-api/api-browser.js
- test/services/twilio-api/api-browser.test.js
Fixes DII-99
Since we are introducing the custom property at operation level to track defaultOutputProperty as part of the [yps changes ](https://code.hq.twilio.com/twilio/yps/pull/87), We also need to make the necessary changes in twilio-cli-core, since the custom property comes wrapped around the property `x-twilio`,  this need to be unwrapped, in the similar fashion as we are doing at the [path level](https://github.com/twilio/twilio-cli-core/blob/main/src/services/twilio-api/api-browser.js#L90-L95).
> fix: added support for default output prop in operation

- .github/workflows/cli-core-audit.yml
- .github/workflows/release.yml
Closes: https://issues.corp.twilio.com/browse/DII-304
> chore: Add Npm Audit workflow

- src/base-commands/base-command.js
- src/services/cli-http-client.js
- test/base-commands/base-command.test.js
- test/base-commands/twilio-client-command.test.js
- test/services/cli-http-client.test.js
Fixes [DII-163](https://issues.corp.twilio.com/browse/DII-163)
This is a regression from https://github.com/twilio/twilio-cli-core/pull/142. Formatting the exit code early failed a check for access denied status. Due to this, the correct error message was not getting displayed to the end user. 
> fix: fix exit code regression

- package.json
> chore: update twilio node mvr version

- src/services/twilio-api/api-browser.js
- test/services/twilio-api/api-browser.test.js
> feat: enable preview domain in cli

- .eslintrc
- .github/scripts/update-release.js
- .github/workflows/release.yml
- .releaserc.json
- README.md
- package.json
- test/release-scripts/get-version-type.test.js
1. Fixed auditing vulnerabilities
2. Updated node versions
3. did 1-1 mapping of cli-core to twilio-cli
> chore: Cli integration test
